"""
CyberAgent Application Data Loader

Loads the JSON outputs generated by the CyberAgent
investigation pipeline.
"""

import json
from pathlib import Path
from typing import Any, Dict, List


# Project root
PROJECT_ROOT = Path(__file__).resolve().parent.parent

# Result directories
RESULTS_DIR = PROJECT_ROOT / "results"

INVESTIGATION_DIR = RESULTS_DIR / "investigation"

THREAT_INTELLIGENCE_DIR = RESULTS_DIR / "threat_intelligence"


# ----------------------------------------------------------------------
# Generic JSON loader
# ----------------------------------------------------------------------

def load_json(path: Path) -> Any:
    """
    Load a JSON file.
    """

    if not path.exists():
        raise FileNotFoundError(
            f"Required file not found:\n{path}"
        )

    with open(
        path,
        "r",
        encoding="utf-8",
    ) as file:

        return json.load(file)


# ----------------------------------------------------------------------
# Normalize JSON records
# ----------------------------------------------------------------------

def normalize_records(data: Any) -> List[Dict[str, Any]]:
    """
    Convert different result JSON structures into
    a simple list of records.
    """

    if isinstance(data, list):
        return data

    if not isinstance(data, dict):
        return []

    possible_keys = [
        "results",
        "samples",
        "profiles",
        "records",
    ]

    for key in possible_keys:

        value = data.get(key)

        if isinstance(value, list):
            return value

    return []


# ----------------------------------------------------------------------
# Load investigation results
# ----------------------------------------------------------------------

def load_investigation_results() -> List[Dict[str, Any]]:
    """
    Load final Investigation Agent results.
    """

    path = (
        INVESTIGATION_DIR
        / "investigation_agent_results.json"
    )

    data = load_json(path)

    return normalize_records(data)


# ----------------------------------------------------------------------
# Load evidence results
# ----------------------------------------------------------------------

def load_evidence_results() -> List[Dict[str, Any]]:
    """
    Load evidence extraction results.
    """

    path = (
        INVESTIGATION_DIR
        / "evidence_extraction_results.json"
    )

    data = load_json(path)

    return normalize_records(data)


# ----------------------------------------------------------------------
# Load threat profiling results
# ----------------------------------------------------------------------

def load_threat_profiles() -> List[Dict[str, Any]]:
    """
    Load threat profiling and severity results.
    """

    path = (
        INVESTIGATION_DIR
        / "threat_profiling_results.json"
    )

    data = load_json(path)

    return normalize_records(data)


# ----------------------------------------------------------------------
# Load threat intelligence
# ----------------------------------------------------------------------

def load_threat_intelligence() -> List[Dict[str, Any]]:
    """
    Load threat intelligence and MITRE results.
    """

    path = (
        THREAT_INTELLIGENCE_DIR
        / "threat_intelligence_results.json"
    )

    data = load_json(path)

    return normalize_records(data)


# ----------------------------------------------------------------------
# Get sample number
# ----------------------------------------------------------------------

def get_sample_number(
    record: Dict[str, Any],
    fallback: int,
) -> int:
    """
    Extract sample number from a record.
    """

    value = record.get(
        "sample_number",
        record.get(
            "sample_index",
            fallback,
        ),
    )

    try:
        return int(value)

    except (
        ValueError,
        TypeError,
    ):
        return fallback


# ----------------------------------------------------------------------
# Build combined sample
# ----------------------------------------------------------------------

def build_sample_dataset() -> List[Dict[str, Any]]:
    """
    Combine investigation, evidence, threat profile,
    and threat intelligence results by sample index.
    """

    investigation = load_investigation_results()

    evidence = load_evidence_results()

    profiles = load_threat_profiles()

    intelligence = load_threat_intelligence()

    samples = []

    total = len(investigation)

    for index in range(total):

        investigation_record = investigation[index]

        evidence_record = (
            evidence[index]
            if index < len(evidence)
            else {}
        )

        profile_record = (
            profiles[index]
            if index < len(profiles)
            else {}
        )

        intelligence_record = (
            intelligence[index]
            if index < len(intelligence)
            else {}
        )

        sample_number = get_sample_number(
            investigation_record,
            index,
        )

        samples.append(
            {
                "sample_number": sample_number,

                "investigation": investigation_record,

                "evidence": evidence_record,

                "threat_profile": profile_record,

                "threat_intelligence": intelligence_record,
            }
        )

    return samples


# ----------------------------------------------------------------------
# Test loader
# ----------------------------------------------------------------------

if __name__ == "__main__":

    print("=" * 70)
    print("CYBERAGENT DATA LOADER TEST")
    print("=" * 70)

    samples = build_sample_dataset()

    print()
    print(
        f"Samples loaded: {len(samples)}"
    )

    for sample in samples:

        print(
            f"Sample: "
            f"{sample['sample_number']}"
        )

    print()
    print("Data loader test completed successfully.")