"""
CyberAgent MITRE ATT&CK Mapper

Maps the threat profile generated by CyberAgent
to candidate MITRE ATT&CK techniques.

The mapper does not claim that a technique occurred.

It produces:
- Candidate techniques
- Relevance
- Confidence
- Reason
- Required corroborating evidence
- Analyst guidance
"""

from src.threat_intelligence.knowledge_base import (
    get_threat_intelligence
)


class MITREMapper:

    def __init__(self):
        pass

    def map_threat(self, threat_class):

        intelligence = get_threat_intelligence(
            threat_class
        )

        techniques = intelligence.get(
            "techniques",
            []
        )

        return {
            "attack_class": threat_class,

            "threat_description": intelligence.get(
                "description"
            ),

            "technique_count": len(
                techniques
            ),

            "candidate_techniques": techniques
        }

    def generate_analyst_guidance(
        self,
        mapping
    ):

        guidance = []

        techniques = mapping.get(
            "candidate_techniques",
            []
        )

        if not techniques:

            guidance.append(
                "No ATT&CK technique can be confidently "
                "inferred from the available evidence."
            )

            return guidance

        for technique in techniques:

            technique_id = technique.get(
                "technique_id"
            )

            technique_name = technique.get(
                "technique_name"
            )

            confidence = technique.get(
                "confidence",
                "Low"
            )

            if technique_id:

                guidance.append(
                    f"Candidate ATT&CK mapping: "
                    f"{technique_id} - "
                    f"{technique_name}. "
                    f"Mapping confidence: "
                    f"{confidence}."
                )

            else:

                guidance.append(
                    f"{technique_name}. "
                    f"Additional telemetry is required "
                    f"before assigning a specific "
                    f"ATT&CK technique."
                )

            required_evidence = technique.get(
                "required_evidence",
                []
            )

            if required_evidence:

                evidence_text = ", ".join(
                    required_evidence
                )

                guidance.append(
                    "Recommended corroborating evidence: "
                    + evidence_text
                    + "."
                )

        return guidance

    def investigate(
        self,
        threat_class
    ):

        mapping = self.map_threat(
            threat_class
        )

        guidance = (
            self.generate_analyst_guidance(
                mapping
            )
        )

        return {
            **mapping,

            "analyst_guidance": guidance,

            "mapping_policy": (
                "ATT&CK mappings are candidate mappings "
                "based on available flow-level evidence. "
                "They should be corroborated with host, "
                "application, authentication, or other "
                "security telemetry before being treated "
                "as confirmed techniques."
            )
        }