"""
CyberAgent Threat Intelligence Runner

Reads the output generated by the Threat Profiling
and Severity Engine.

Adds:
- Local threat intelligence
- MITRE ATT&CK candidate mappings
- Analyst guidance
- Investigation requirements
"""

import json
from pathlib import Path

from src.threat_intelligence.mitre_mapper import (
    MITREMapper
)


PROJECT_ROOT = Path(__file__).resolve().parents[2]

INPUT_FILE = (
    PROJECT_ROOT
    / "results"
    / "investigation"
    / "threat_profiling_results.json"
)

OUTPUT_DIR = (
    PROJECT_ROOT
    / "results"
    / "threat_intelligence"
)

OUTPUT_FILE = (
    OUTPUT_DIR
    / "threat_intelligence_results.json"
)


def load_threat_profiles():

    print(
        "Loading threat profiling results..."
    )

    if not INPUT_FILE.exists():

        raise FileNotFoundError(
            "Threat profiling result file was not found:\n"
            f"{INPUT_FILE}"
        )

    with open(
        INPUT_FILE,
        "r",
        encoding="utf-8"
    ) as file:

        data = json.load(file)

    return data


def main():

    print("=" * 70)
    print(
        "CYBERAGENT THREAT INTELLIGENCE + "
        "MITRE ATT&CK MAPPING"
    )
    print("=" * 70)

    data = load_threat_profiles()

    results = data.get(
        "results",
        []
    )

    print(
        f"Threat profiles loaded: {len(results)}"
    )

    mapper = MITREMapper()

    intelligence_results = []

    for index, item in enumerate(results):

        print()
        print("-" * 70)

        print(
            f"Analyzing threat profile {index}"
        )

        threat_profile = item.get(
            "threat_profile",
            {}
        )

        severity = item.get(
            "severity_assessment",
            {}
        )

        threat_class = threat_profile.get(
            "predicted_threat",
            "Unknown"
        )

        severity_score = severity.get(
            "severity_score",
            0
        )

        severity_level = severity.get(
            "severity_level",
            "Informational"
        )

        mapping = mapper.investigate(
            threat_class
        )

        combined_result = {

            "sample_number": item.get(
                "sample_number",
                index
            ),

            "threat_class": threat_class,

            "severity_assessment": {

                "score": severity_score,

                "level": severity_level
            },

            "threat_intelligence": mapping
        }

        intelligence_results.append(
            combined_result
        )

        print(
            "Threat class       : "
            f"{threat_class}"
        )

        print(
            "Severity level     : "
            f"{severity_level}"
        )

        print(
            "Severity score     : "
            f"{severity_score}/100"
        )

        print(
            "Candidate mappings : "
            f"{mapping['technique_count']}"
        )

        for technique in mapping[
            "candidate_techniques"
        ]:

            technique_id = (
                technique.get(
                    "technique_id"
                )
            )

            technique_name = (
                technique.get(
                    "technique_name"
                )
            )

            if technique_id:

                print(
                    f"  {technique_id} - "
                    f"{technique_name}"
                )

            else:

                print(
                    f"  No specific ATT&CK ID: "
                    f"{technique_name}"
                )

    OUTPUT_DIR.mkdir(
        parents=True,
        exist_ok=True
    )

    output = {

        "system": "CyberAgent",

        "phase": (
            "Threat Intelligence and "
            "MITRE ATT&CK Mapping"
        ),

        "description": (
            "Evidence-aware threat intelligence "
            "and candidate MITRE ATT&CK mappings "
            "generated from CyberAgent threat profiles."
        ),

        "mapping_policy": (
            "Mappings are candidate associations "
            "and require corroborating telemetry "
            "before being considered confirmed."
        ),

        "samples_analyzed": len(
            intelligence_results
        ),

        "results": intelligence_results
    }

    with open(
        OUTPUT_FILE,
        "w",
        encoding="utf-8"
    ) as file:

        json.dump(
            output,
            file,
            indent=4
        )

    print()
    print("=" * 70)
    print(
        "Threat intelligence analysis completed."
    )

    print(
        f"Saved to: {OUTPUT_FILE}"
    )

    print("=" * 70)


if __name__ == "__main__":
    main()